#!/bin/bash
export DATABASE_URL='postgresql://postgres:postgres@localhost/testdb'
export SECRET_KEY=b'8v\xf9\x15\x1c\xa1\xad\x04\x94a\xae\x91\xd0uZ\xb4'
export FLASK_APP=run.py


if [ "$1" == "run" ]; then
    # exec python run.py
    # exec flask run -p 5300
    exec gunicorn run:app -k eventlet -b :5900
elif [ "$1" == "shell" ]; then
    exec flask shell
elif [ "$1" == "init" ]; then
    exec flask db init
elif [ "$1" == "migrate" ]; then
    exec flask db migrate
elif [ "$1" == "upgrade" ]; then
    exec flask db upgrade
else
    echo "Usage: ./dev_start run; ./dev_start migrate; \
    ./dev_start upgrade; ./dev_start shell"
    exit
        
fi

# exec flask run
# exec gunicorn -b :5000 --access-logfile - --error-logfile - run_api:app -k gevent --workers 1 --timeout 120